### ISSUE TITLE
Algorithm consulting

### ISSUE THREAD

**Issue by Sisyphus-pandapia** [artak-kirakosyan/elg5376_watermarking#1]
"A course project on implementing a selected algorithm from one of the published papers"
Could you provide the specific name of the paper that reproduces this project? Thanks a lot for your help, I want to learn more details about this algorithm.

**Comment by artak-kirakosyan** [comment]
Hi.
Glad to see the interest :)
Here is the link to the paper: https://asmp-eurasipjournals.springeropen.com/articles/10.1186/s13636-014-0037-2
